apiVersion: apps/v1
kind: Deployment
metadata:
  name: argo-server
  namespace: argo
spec:
  replicas: 1
  selector:
    matchLabels:
      app: argo-server
  template:
    metadata:
      labels:
        app: argo-server
    spec:
      containers:
        - name: argo-server
          image: quay.io/argoproj/argo-server:v3.5.10
          args:
            - server
            - --auth-mode=server
            - --insecure
          ports:
            - containerPort: 2746
---
apiVersion: v1
kind: Service
metadata:
  name: argo-server
  namespace: argo
spec:
  selector:
    app: argo-server
  ports:
    - name: http
      port: 2746
      targetPort: 2746
  type: ClusterIP
